// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about-bihe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about-bihe">> = Specific
  const handler = {} as typeof import("../../src/app/about-bihe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/academics/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/academics/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/academics/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admissions/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admissions/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/admissions/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alumni/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/alumni/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alumni/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni/about">> = Specific
  const handler = {} as typeof import("../../src/app/alumni/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alumni/events/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni/events/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/alumni/events/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alumni/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni/events">> = Specific
  const handler = {} as typeof import("../../src/app/alumni/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alumni/gallery/[imageId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni/gallery/[imageId]">> = Specific
  const handler = {} as typeof import("../../src/app/alumni/gallery/[imageId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alumni/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/alumni/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alumni/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni/home">> = Specific
  const handler = {} as typeof import("../../src/app/alumni/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alumni/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni">> = Specific
  const handler = {} as typeof import("../../src/app/alumni/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/alumni/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alumni/register">> = Specific
  const handler = {} as typeof import("../../src/app/alumni/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/annual-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/annual-reports">> = Specific
  const handler = {} as typeof import("../../src/app/annual-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/audit-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/audit-report">> = Specific
  const handler = {} as typeof import("../../src/app/audit-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/b-com/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/b-com">> = Specific
  const handler = {} as typeof import("../../src/app/b-com/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bca/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bca">> = Specific
  const handler = {} as typeof import("../../src/app/bca/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/constituent-units/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/constituent-units">> = Specific
  const handler = {} as typeof import("../../src/app/constituent-units/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/controller-of-examination/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/controller-of-examination">> = Specific
  const handler = {} as typeof import("../../src/app/controller-of-examination/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/finance-section/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance-section">> = Specific
  const handler = {} as typeof import("../../src/app/finance-section/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gallery/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/gallery/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/governing-bodies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/governing-bodies">> = Specific
  const handler = {} as typeof import("../../src/app/governing-bodies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/info-corner/[slug]/[itemSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/info-corner/[slug]/[itemSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/info-corner/[slug]/[itemSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/info-corner/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/info-corner/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/info-corner/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/info-corner/circulars-and-notices/[noticeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/info-corner/circulars-and-notices/[noticeId]">> = Specific
  const handler = {} as typeof import("../../src/app/info-corner/circulars-and-notices/[noticeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/institutional-development-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/institutional-development-plan">> = Specific
  const handler = {} as typeof import("../../src/app/institutional-development-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/internal-complaint-committee/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/internal-complaint-committee">> = Specific
  const handler = {} as typeof import("../../src/app/internal-complaint-committee/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/memorandum-of-association/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memorandum-of-association">> = Specific
  const handler = {} as typeof import("../../src/app/memorandum-of-association/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/news/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/news/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news">> = Specific
  const handler = {} as typeof import("../../src/app/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ombudsperson/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ombudsperson">> = Specific
  const handler = {} as typeof import("../../src/app/ombudsperson/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/principal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/principal">> = Specific
  const handler = {} as typeof import("../../src/app/principal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recognition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recognition">> = Specific
  const handler = {} as typeof import("../../src/app/recognition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/research/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/research/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/research/research-and-development-cell/[projectSlug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research/research-and-development-cell/[projectSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/research/research-and-development-cell/[projectSlug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/student-life/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student-life/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/student-life/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/student-life/placement-cell-and-activities/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student-life/placement-cell-and-activities/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/student-life/placement-cell-and-activities/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/student-life/sports-facilities/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student-life/sports-facilities/events">> = Specific
  const handler = {} as typeof import("../../src/app/student-life/sports-facilities/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/[[...slug]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/[[...slug]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alumni/register/captcha/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/register/captcha">> = Specific
  const handler = {} as typeof import("../../src/app/api/alumni/register/captcha/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alumni/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/alumni/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alumni/register/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alumni/register/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/alumni/register/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/captcha/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact/captcha">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/captcha/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gallery/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gallery/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/gallery/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gallery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/api/gallery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/revalidate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/revalidate">> = Specific
  const handler = {} as typeof import("../../src/app/api/revalidate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/assets/[[...slug]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/assets/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../src/app/assets/[[...slug]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/storage/[[...slug]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/storage/[[...slug]]">> = Specific
  const handler = {} as typeof import("../../src/app/storage/[[...slug]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
